### ISSUE TITLE
Flutter connection with ODBC dbview (not a issue, but research)

### ISSUE THREAD

**Issue by dakanadaka** [jcmellado/dart-odbc#2]
Hello there,

I have very old database https://www.elevatesoft.com/products?category=dbisam and I would like to connect with Flutter windows app..

I did made connection with QT and as I could see it needed to be 32bit application. 

here is the code from QT:
` db = QSqlDatabase::addDatabase("QODBC");
    db.setHostName("dbisam_vec");
    if(db.open()){
        qInfo() << "database  connected";
       return true;
    } else {
       qInfo() << db.lastError().text();
       return false;
   }`

dbisam_vec I set it in the microsoft odbc Data Source Administrator (32 bit) 
DBISAM 4 ODBC Driver

This is temporary solution to connect to this database, later on I will switch to other database.
But for now I need this one to connect with odbc driver with flutter.

Is this possible?

**Comment by jcmellado** [comment]
This project is a bit old (last commit was 8 years ago), not sure if the library will work with Flutter.

**Comment by dakanadaka** [comment]
Do you have any other suggestion?

**Comment by jcmellado** [comment]
No, sorry
